### ISSUE TITLE
运行时有些错误

### ISSUE THREAD

**Issue by ruonani** [StarYuhen/Yun#1]
运行时报了几个错误不知道咋解决 
想请教下大佬 qq:488656533

**Comment by StarYuhen** [comment]
没有报错日志，自己发，不加q

**Comment by ruonani** [comment]
![2](https://github.com/StarYuhen/Yun/assets/162281533/a4d81fd8-180b-40db-827a-1a3232ba23af)
创建成功后就这样了

**Comment by StarYuhen** [comment]
记得把高德之类的key给写入配置文件

**Comment by StarYuhen** [comment]
> ![2](https://private-user-images.githubusercontent.com/162281533/310036638-a4d81fd8-180b-40db-827a-1a3232ba23af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgwNDMsIm5iZiI6MTcwOTYyNzc0MywicGF0aCI6Ii8xNjIyODE1MzMvMzEwMDM2NjM4LWE0ZDgxZmQ4LTE4MGItNDBkYi04MjdhLTFhMzIzMmJhMjNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwODM1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGYyNTEyNGJlNjNmNDA3OWVhZGRiZjZkNjZlZjJiMTEwMDM1YjAxYmQzMDcxZjMxMWViNDEyZjQ0ZTZlYTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HBdYM8wcOf4YTOOObdkTbLroN-xXe5L8-LLakVkxUEQ) 创建成功后就这样了

记得把高德之类的key给写入配置文件

**Comment by StarYuhen** [comment]
> ![2](https://private-user-images.githubusercontent.com/162281533/310036638-a4d81fd8-180b-40db-827a-1a3232ba23af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjgwNDMsIm5iZiI6MTcwOTYyNzc0MywicGF0aCI6Ii8xNjIyODE1MzMvMzEwMDM2NjM4LWE0ZDgxZmQ4LTE4MGItNDBkYi04MjdhLTFhMzIzMmJhMjNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwODM1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGYyNTEyNGJlNjNmNDA3OWVhZGRiZjZkNjZlZjJiMTEwMDM1YjAxYmQzMDcxZjMxMWViNDEyZjQ0ZTZlYTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HBdYM8wcOf4YTOOObdkTbLroN-xXe5L8-LLakVkxUEQ) 创建成功后就这样了

不懂得配置就看原仓库，我只是魔改了代码，并未更改配置文件

**Comment by StarYuhen** [comment]
> 运行时报了几个错误不知道咋解决 想请教下大佬 qq:488656533

错误已在最新版修复
