### ISSUE TITLE
运行的时候报错了，想请教一下您

### ISSUE THREAD

**Issue by SuiK233** [StarYuhen/Yun#3]
在处理第一个点的时候报错了
![PixPin_2024-03-05_18-39-52](https://github.com/StarYuhen/Yun/assets/93854815/fda3b8e9-a108-4cd1-9537-05ea69c056ef)
我搜索了一下，好像是base64 编码或解码操作时的问题，但我水平不行，解决不了

**Comment by Warbin-Hub** [comment]
一样的报错

**Comment by StarYuhen** [comment]
> 在处理第一个点的时候报错了 ![PixPin_2024-03-05_18-39-52](https://private-user-images.githubusercontent.com/93854815/310083992-fda3b8e9-a108-4cd1-9537-05ea69c056ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzczMzksIm5iZiI6MTcwOTYzNzAzOSwicGF0aCI6Ii85Mzg1NDgxNS8zMTAwODM5OTItZmRhM2I4ZTktYTEwOC00Y2QxLTk1MzctMDVlYTY5YzA1NmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWM3MjE1ZmMyMzI1ZTcyMzRkOWMzN2MwN2MzYmRiM2YwNDQwMGZlZTc4NjRlNWNiNTY4ZTkyYzJlYjcwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7WN851eS-iqeCVUcsmA25hOfXPdTK9DS-HP71jDyOU) 我搜索了一下，好像是base64 编码或解码操作时的问题，但我水平不行，解决不了

发QQ给我，同时加上好友后将配置文件发我，包括学校及学号，我将修复这个问题，若建议明日将关闭该issues

**Comment by SuiK233** [comment]
> > 在处理第一个点的时候报错了 ![PixPin_2024-03-05_18-39-52](https://private-user-images.githubusercontent.com/93854815/310083992-fda3b8e9-a108-4cd1-9537-05ea69c056ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzczMzksIm5iZiI6MTcwOTYzNzAzOSwicGF0aCI6Ii85Mzg1NDgxNS8zMTAwODM5OTItZmRhM2I4ZTktYTEwOC00Y2QxLTk1MzctMDVlYTY5YzA1NmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWM3MjE1ZmMyMzI1ZTcyMzRkOWMzN2MwN2MzYmRiM2YwNDQwMGZlZTc4NjRlNWNiNTY4ZTkyYzJlYjcwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7WN851eS-iqeCVUcsmA25hOfXPdTK9DS-HP71jDyOU) 我搜索了一下，好像是base64 编码或解码操作时的问题，但我水平不行，解决不了
> 
> 发QQ给我，同时加上好友后将配置文件发我，包括学校及学号，我将修复这个问题，若建议明日将关闭该issues

好的好的，这是我的qq，3396475737，感谢

**Comment by ruonani** [comment]
> > 在处理第一个点的时候报错了 ![PixPin_2024-03-05_18-39-52](https://private-user-images.githubusercontent.com/93854815/310083992-fda3b8e9-a108-4cd1-9537-05ea69c056ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzczMzksIm5iZiI6MTcwOTYzNzAzOSwicGF0aCI6Ii85Mzg1NDgxNS8zMTAwODM5OTItZmRhM2I4ZTktYTEwOC00Y2QxLTk1MzctMDVlYTY5YzA1NmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWM3MjE1ZmMyMzI1ZTcyMzRkOWMzN2MwN2MzYmRiM2YwNDQwMGZlZTc4NjRlNWNiNTY4ZTkyYzJlYjcwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7WN851eS-iqeCVUcsmA25hOfXPdTK9DS-HP71jDyOU) 我搜索了一下，好像是base64 编码或解码操作时的问题，但我水平不行，解决不了
> 
> 发QQ给我，同时加上好友后将配置文件发我，包括学校及学号，我将修复这个问题，若建议明日将关闭该issues
我的问题跟他一样大佬  qq:488656533  谢谢您

**Comment by StarYuhen** [comment]
> 一样的报错

新版本已修复，今晚更新

**Comment by StarYuhen** [comment]
> > > 在处理第一个点的时候报错了 ![PixPin_2024-03-05_18-39-52](https://private-user-images.githubusercontent.com/93854815/310083992-fda3b8e9-a108-4cd1-9537-05ea69c056ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzczMzksIm5iZiI6MTcwOTYzNzAzOSwicGF0aCI6Ii85Mzg1NDgxNS8zMTAwODM5OTItZmRhM2I4ZTktYTEwOC00Y2QxLTk1MzctMDVlYTY5YzA1NmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWM3MjE1ZmMyMzI1ZTcyMzRkOWMzN2MwN2MzYmRiM2YwNDQwMGZlZTc4NjRlNWNiNTY4ZTkyYzJlYjcwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7WN851eS-iqeCVUcsmA25hOfXPdTK9DS-HP71jDyOU) 我搜索了一下，好像是base64 编码或解码操作时的问题，但我水平不行，解决不了
> > 
> > 
> > 发QQ给我，同时加上好友后将配置文件发我，包括学校及学号，我将修复这个问题，若建议明日将关闭该issues
> > 我的问题跟他一样大佬  qq:488656533  谢谢您

今晚修复，等会儿测试更新github
