### ISSUE TITLE
配置运行后提示版本过低，应用商店最新云运动版本号为3.0.0

### ISSUE THREAD

**Issue by PapiLight** [StarYuhen/Yun#4]
{"msg":"版本过低，请前往应用市场更新！","code":500}
任务失败！检查token、高德地图开发者密钥或网络设置
string argument should contain only ASCII characters

**Comment by StarYuhen** [comment]
> {"msg":"版本过低，请前往应用市场更新！","code":500} 任务失败！检查token、高德地图开发者密钥或网络设置 string argument should contain only ASCII characters

应该是你学校的接口问题，部分学校的接口还是老版本，请使用原github仓库查看，本就是最新版的3.0.0接口

**Comment by Zirconium233** [comment]
确实是学校接口问题，我的版本发布了，解决3.0.0问题，虽然这位大佬跟早解决了问题，不过接口和合工大的不适配，所以我上传了我的，提供更多的技术细节参考：https://github.com/Zirconium233/yunForNewVerison
