### ISSUE TITLE
运行后一直输出“开始标记打卡点，第N次尝试”

### ISSUE THREAD

**Issue by PapiLight** [StarYuhen/Yun#5]
一直获取不了打卡点

**Comment by StarYuhen** [comment]
最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。
明天会关闭该issues，请尽快查看最新版代码

**Comment by PapiLight** [comment]
> 最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。 明天会关闭该issues，请尽快查看最新版代码
日志如下:

开始标记打卡点...
第1次尝试...
第2次尝试...
第3次尝试...

尝试几百次后报错，尝试用多个学校的的云运动账号尝试均如此

**Comment by PapiLight** [comment]
> 最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。 明天会关闭该issues，请尽快查看最新版代码
日志如下:

开始标记打卡点...
第1次尝试...
第2次尝试...
第3次尝试...

尝试几百次后报错，尝试用多个学校的的云运动账号尝试均如此

**Comment by StarYuhen** [comment]
> > 最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。 明天会关闭该issues，请尽快查看最新版代码
> > 日志如下:
> 
> 开始标记打卡点... 第1次尝试... 第2次尝试... 第3次尝试...
> 
> 尝试几百次后报错，尝试用多个学校的的云运动账号尝试均如此

请将参数截图完整，从最开始到发生这样的结尾

**Comment by StarYuhen** [comment]
> > 最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。 明天会关闭该issues，请尽快查看最新版代码
> > 日志如下:
> 
> 开始标记打卡点... 第1次尝试... 第2次尝试... 第3次尝试...
> 
> 尝试几百次后报错，尝试用多个学校的的云运动账号尝试均如此

请将云运动账号密码+学校 私发邮箱 3446623843@qq.com，另外请确认自己用的最新版，最新版测试过账号，没会引发你目前的问题，请勿在一个ip登录多个账号

**Comment by yejiu7411** [comment]
> 最新版已修复，如果有问题请查看旧版仓库关于打卡点的问题，请给予详细日志。 明天会关闭该issues，请尽快查看最新版代码

加下你,问问其他问题

**Comment by PapiLight** [comment]
你好，重新拾取学校主干道坐标点后获取打卡点成功跑完全程成绩合格，但登录云运动后不显示跑步路线，配置文件除device_id和map_kay外无更改，这是正常现象吗？

**Comment by PapiLight** [comment]
你好，重新拾取学校主干道坐标点后获取打卡点成功跑完全程成绩合格，但登录云运动后不显示跑步路线，配置文件除device_id和map_kay外无更改，这是正常现象吗？
![Screenshot_2024-03-06-12-26-33-69_31578d47161a41a](https://github.com/StarYuhen/Yun/assets/63484850/392368b0-ded8-4e71-878e-896ad66063f5)

**Comment by StarYuhen** [comment]
> 你好，重新拾取学校主干道坐标点后获取打卡点成功跑完全程成绩合格，但登录云运动后不显示跑步路线，配置文件除device_id和map_kay外无更改，这是正常现象吗？ ![Screenshot_2024-03-06-12-26-33-69_31578d47161a41a](https://private-user-images.githubusercontent.com/63484850/310361397-392368b0-ded8-4e71-878e-896ad66063f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTk4NzQsIm5iZiI6MTcwOTY5OTU3NCwicGF0aCI6Ii82MzQ4NDg1MC8zMTAzNjEzOTctMzkyMzY4YjAtZGVkOC00ZTcxLTg3OGUtODk2YWQ2NjA2M2Y1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA0MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTE4NTBlYjgzOGM3ZTU5ZjBmZTFkZTFiZTc5Y2RkZmJlOWU2MjM2ZmQ1ZmNlYTcwM2Q0OGY2OTcxMzg3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFCnN2KL7vmZu1GK8DgPWbMJ0sxJ3SueQCye1ae-2f8)

说明打卡点位有问题，获取和经过点位失败

**Comment by StarYuhen** [comment]
![屏幕截图 2022-09-21 101703](https://github.com/StarYuhen/Yun/assets/58671667/b6f5a7d9-3b93-436c-ba8f-0e6e865d2bb1)
请按照README.MD的说明解决该问题，问题已解决，关闭该issues

**Comment by StarYuhen** [comment]
![屏幕截图 2024-03-06 124032](https://github.com/StarYuhen/Yun/assets/58671667/1a1bae77-9600-4176-9ebb-76ccd8d2f427)
请按照README.MD介绍的解决办法，解决多次尝试的问题，该问题已解决，关闭该issues

**Comment by StarYuhen** [comment]
> ![屏幕截图 2024-03-06 124032](https://private-user-images.githubusercontent.com/58671667/310363242-1a1bae77-9600-4176-9ebb-76ccd8d2f427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDA0MjUsIm5iZiI6MTcwOTcwMDEyNSwicGF0aCI6Ii81ODY3MTY2Ny8zMTAzNjMyNDItMWExYmFlNzctOTYwMC00MTc2LTllYmItNzZjY2Q4ZDJmNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA0NDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZTE4ODUzNzg1ODY4MDZlYjExNThjYWJmMWJkYjYxNjg5Yzg0ZTZiMWM4YjA2MDZlMzE0MTk2ZjY2NThhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRNcsfUUTs7jygIJPhJhYNPb3KO9V83dngMaxogxocs) 请按照README.MD介绍的解决办法，解决多次尝试的问题，该问题已解决，关闭该issues

 # print("data：", data) 去除注释，即去除# 变成print("data：", data) ，可以拿到参数值
